umbraco/Umbraco.Playwright.Testhelpers

- lib/helpers/ConstantHelper.ts
Adding two more actions to the actions section for commonly occuring strings in acceptance tests
> New actions added to the contants helper

- lib/helpers/ApiHelpers.ts
- lib/helpers/ConstantHelper.ts
- lib/helpers/TranslationApiHelper.ts
- lib/helpers/UserApiHelper.ts
Adding support for translation acceptance tests.
> Added helpers for user and translation

- lib/helpers/ApiHelpers.ts
- lib/helpers/TemporaryFileApiHelper.ts
- package.json
Created a method for posting MultiPartForm files.
Updated our TemporaryApi to use it.
> Added a postMultiPartFrom method for posting files

- lib/helpers/DatatypeApiHelper.ts
- package-lock.json
- package.json
Added a create slider datatype for adding a slider with a default value
> Added a create slider datatype

- lib/helpers/ConstantHelper.ts
- lib/helpers/UiHelpers.ts
- lib/helpers/index.ts
- package-lock.json
- package.json
Updated goToSection so the method checks if all the sections are visible before clicking.
Added constants for sections.
> V2 Updated LogViewerHelper

- lib/helpers/ApiHelpers.ts
- lib/helpers/TemplateApiHelper.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
This PR is used for the New BackOffice in v14/dev
Updated existing TemplateHelpers
Updated notification methods and added a method for going to a template
Fixed indentation
Bumped Version
1. Go into the file README.md and find the section for 'Testing your changes locally'
2. Run the NewBackOffice in v14/dev.
3. Test if the helpers function as expected by creating simple tests using the helpers
> v2 Updated TestHelpers for Templates

- lib/helpers/ScriptApiHelper.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
Added UI helper for 'goToScript', and added comments for clarification.
Cleaned up the current scripApiHelper. Added additional methods. Cleaned up indentation.
Bumped version
> V2 updated Scripthelpers

- lib/helpers/StylesheetApiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
Added StylesheetUiHelper 
Imported StylesheetUiHelper into UiHelper and added goToBackOffice and waitForTimeout to avoid using page in tests
Updated StylesheetApiHelper
Bumped version
> V2 updated Stylesheet Helpers

- lib/helpers/ApiHelpers.ts
- lib/helpers/DocumentTypeApiHelper.ts
- lib/helpers/MediaTypeApiHelper.ts
- lib/helpers/WebhookApiHelper.ts
- package-lock.json
- package.json
Added a Webhook Api Helper,
Added getByName to MediaTypes and createDefaultDocumentType to DocumentTypes.
Added a Delete method for deleting the Webhooks.
Bumped version
> Added Webhook helpers

- lib/helpers/DictionaryApiHelper.ts
- lib/helpers/DictionaryUiHelper.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
Updated api helpers of Dictionary
Added ui helpers of Dictionary
Imported DictionaryUiHelper into UiHelpers
Bumped version of helper
> V2 Updated api and ui helpers of Dictionary

- lib/helpers/DictionaryApiHelper.ts
- lib/helpers/DictionaryUiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/ScriptUiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/TemplateUiHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
This PR focuses on updating the base class implementation:
- UiBaseLocators: contains common locators and actions 
- UiHelper: creates instance of all ui page objects and contains common methods interact with page such as wait/reload/ goto page
- ui helper of each page will extend the UiBaseLocators to avoid the redundance code
And this PR also changes the name of method in DictionaryApiHelper from exist() to doesExist().
> V2 Updated the base class

- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/UiHelpers.ts
This PR focuses on adding Dat Type test helpers to perform acceptance tests for basic functions of Data Type, approved color and label. It includes:
- Updated api test helper for Data Type
- Added ui test helper for basic functions of Data Type, Approved color and Label
> V2 Added DataType test helper to perform acceptance tests  for basic functions, approved color and label

- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Added a timeout for the goToSection method. Hopefully this will fix our pipeline
> Added a timeout for the goToSection method

- lib/helpers/DictionaryApiHelper.ts
- lib/helpers/LanguageApiHelper.ts
- lib/helpers/LanguageUiHelper.ts
- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
Added api helpers for Language
Added ui helpers for Language
Updated api helper of Dictionary as the method getAll() is changed
Bumped version
> V2 Added test helpers for Language

- lib/helpers/PartialViewApiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
This PR focuses on updating the test helper to fixing the failed tests of Partial View and adding the tests for Query Builder in Partial View. It includes:
- Updated api test helper for Partial View as the endpoints are changed
- Updated ui test helper for Partial View as the UI's changes
- Updated UiBaseLocator to add method for adding query builder and rename
- Bumped version
> V2 Updated test helper for Partial View

- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/PackageUiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/ScriptApiHelper.ts
- lib/helpers/ScriptUiHelper.ts
- lib/helpers/StylesheetApiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/TemplateUiHelper.ts
- lib/helpers/UiBaseLocators.ts
Updated Script, Stylesheet, Template and UIBase.
> V2 Updated TestHelpers

- lib/helpers/TemplateUiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Added method for checking if a masterTemplate is visible or not.
Added locator in the uiBaseLocators for clicking a button with specific name. Also added waitForTimeout
> V2 Updated template Helper

- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
- Updated insertDictionaryByName method due to the UI changes
- Bumped version
> V2 Updated test helper to fix the failing tests of Partial View

- lib/helpers/UiHelpers.ts
- package-lock.json
- package.json
Added goBackPage method to fix Dashboard tests
> V2 Added goBackPage method to fix Dashboard tests

- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/PackageUiHelper.ts
- lib/helpers/UiBaseLocators.ts
Added ui helper for Content Picker and Tags
Added ui helper for Richtext Editor
Added ui helpers for MultiURLPicker and Multiple Media Picker
Added ui helpers for Dropdown
Added ui helpers for Checkboxlist
Added ui helpers for True/false
Updated api and ui helper for DataType due to fix the failing tests due to ui changes
> V2 Updated test helper for DataType

- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Update the locator of createThreeDots button due to the UI changes
> V2 Fixed failing test on pipeline 

- package-lock.json
- package.json
Bumped back to the previous version
> V2 Bumped back to the previous version

- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/DictionaryUiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/ScriptUiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/UiBaseLocators.ts
Updated test helper to fix the acceptance tests of delete function
> V2 Updated test helper to fix the acceptance tests of delete function

- lib/helpers/ExamineManagementUiHelper.ts
- lib/helpers/HealthCheckUiHelper.ts
- lib/helpers/LogViewerUiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/PublishedStatusUiHelper.ts
- lib/helpers/ScriptUiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/TemplateUiHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/WelcomeDashboardUiHelper.ts
- package-lock.json
- package.json
- playwright.config.ts
Apply best practices to speed up the tests:
- Block unnecessary resources when login
- Removed the hard waits (waitForTime)
> V2 Updated test helpers to speed up the acceptance tests

- lib/helpers/ApiHelpers.ts
- package-lock.json
- package.json
The auth is not working on the pipeline, so I added some logs to see what could be the issues on the pipeline
> V2 made adjustments to the auth

- lib/helpers/ContentUiHelper.ts
- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/StylesheetApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
To fix the tests for adding a start node in Data Type and creating a stylesheet.
> V2 Fixed Data Type test helpers

- lib/helpers/LanguageUiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Also update locator related to folder name text box to fix the failing tests
> V2 Update test helpers for Languages, Stylesheet

- lib/helpers/ContentUiHelper.ts
- lib/helpers/DocumentApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Also fix the failing tests for Media Picker and Image Cropper in the Content section
> V2 Updated the Multiple Media Picker test helper

- lib/helpers/ContentUiHelper.ts
- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/LogViewerUiHelper.ts
- lib/helpers/MediaApiHelper.ts
- lib/helpers/MediaUiHelper.ts
- lib/helpers/TemporaryFileApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/UserUiHelper.ts
- package-lock.json
- package.json
Focused on fixing the failing tests on the E2E nightly pipeline
> V2 Update E2E helpers

- lib/helpers/ApiHelpers.ts
- lib/helpers/LoginApiHelper.ts
- lib/helpers/testExtension.ts
- package-lock.json
- package.json
We've been running into some issues where the token was invalid. This addition allows us to get a new token.
> V2 Added login reauth

- lib/helpers/ContentUiHelper.ts
- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DocumentTypeApiHelper.ts
- package-lock.json
- package.json
Added test helper for Content with these document type properties:
- Allow as root
- Allowed child nodes
- Collections
And fix the List View Media tests
> V2 Added test helper for Content with document type properties

- lib/helpers/ApiHelpers.ts
- lib/helpers/LoginApiHelper.ts
- package-lock.json
- package.json
We are currently experiencing issues on our E2E tests for SQL server on the pipeline, hopefully this fixes the issue
> V2 Update login helper

- lib/helpers/DocumentApiHelper.ts
- package-lock.json
- package.json
As I haven't committed the missing code that fixes the comments for the PRhttps://github.com/umbraco/Umbraco.Playwright.Testhelpers/pull/143, I create this PR to fix it
> V2 Updated api helper for Document

- lib/helpers/ContentRenderUiHelper.ts
- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DocumentApiHelper.ts
- lib/helpers/TemplateApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
Also updated the media ui helper to fix the failing tests
> V2 Added test helpers for rendering content with different values

- lib/helpers/UiBaseLocators.ts
- lib/helpers/UserUiHelper.ts
- package-lock.json
- package.json
Updated locators as they have been changed in the frontend
> V15 updated test helpers for failing tests

- lib/helpers/ApiHelpers.ts
- lib/helpers/ConstantHelper.ts
- lib/helpers/ContentUiHelper.ts
- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DataTypeUiHelper.ts
- lib/helpers/DictionaryUiHelper.ts
- lib/helpers/DocumentApiHelper.ts
- lib/helpers/DocumentBlueprintUiHelper.ts
- lib/helpers/DocumentTypeApiHelper.ts
- lib/helpers/LanguageUiHelper.ts
- lib/helpers/LogViewerUiHelper.ts
- lib/helpers/LoginApiHelper.ts
- lib/helpers/MediaApiHelper.ts
- lib/helpers/MediaUiHelper.ts
- lib/helpers/MemberGroupUiHelper.ts
- lib/helpers/MemberUiHelper.ts
- lib/helpers/NotificationConstantHelper.ts
- lib/helpers/PackageUiHelper.ts
- lib/helpers/PartialViewUiHelper.ts
- lib/helpers/ScriptUiHelper.ts
- lib/helpers/StylesheetUiHelper.ts
- lib/helpers/TemplateUiHelper.ts
- lib/helpers/TemporaryFileApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/UserApiHelper.ts
- lib/helpers/UserGroupUiHelper.ts
- lib/helpers/UserUiHelper.ts
- lib/helpers/testExtension.ts
- package-lock.json
- package.json
This PR focuses on cherrypicking all of the changes that are relevant in V15 from V2.
> V15 Cherrypick from V2

- lib/helpers/DocumentTypeApiHelper.ts
- package-lock.json
- package.json
Updated test helper to fix the issue: https://github.com/umbraco/Umbraco-CMS/issues/18252
> V15 Updated test helper to fix the issue 18252

- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
There has been changes to the reload buttons from 'reload' to 'reload children'
> V15 updated reload locators

- lib/helpers/UiBaseLocators.ts
- package-lock.json
- package.json
This PR reverts the previous change made as it resulted in failing tests
> V15 changed reload locator

- lib/helpers/DocumentTypeUiHelper.ts
- package-lock.json
- package.json
The Vary By Culture Toggle has been renamed to Shared Across Cultures
> V16 changed label for Vary By culture 

- package-lock.json
- package.json
Bumped version since 15.0.47 has already been released
> V15 Bumped version

- lib/helpers/ContentUiHelper.ts
- lib/helpers/NotificationConstantHelper.ts
- package-lock.json
- package.json
Need to update test helper due to this changes (https://github.com/umbraco/Umbraco-CMS/pull/19159)
> V16 Updated test helper for publishing content

- lib/helpers/ContentUiHelper.ts
- package-lock.json
- package.json
We were having issues with clicking block on the pipeline for the second level block tests
> V15 update second level block

- lib/helpers/ConstantHelper.ts
- lib/helpers/NotificationConstantHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/UserGroupApiHelper.ts
- lib/helpers/UserGroupUiHelper.ts
- package-lock.json
- package.json
Also updated api helper for user group as currently the "Browse Node" permission is changed to "Read"
> V16 Updated test helper for default property value permission 

- lib/helpers/ContentUiHelper.ts
- lib/helpers/DataTypeApiHelper.ts
- lib/helpers/DocumentTypeApiHelper.ts
- lib/helpers/UiBaseLocators.ts
- lib/helpers/UserGroupApiHelper.ts
- package-lock.json
- package.json
And also add more waits after clicking save button to fix the failing tests. This is just a temporary solution as the implementation of the notification verification is still in progress.
> V16 Updated test helper for granular property value permission

- lib/helpers/ContentUiHelper.ts
- package-lock.json
- package.json
Updated ui helper for clicking the block in RTE due to UI changes in the PR #[19811](https://github.com/umbraco/Umbraco-CMS/pull/19811)
> V16 Updated test helper for block in RTE
